version: '3'
services:
  chatgpt:
    image: sheepgreen/chatgpt-wework
#    environment:
#      - CHATGPT_BASE_URL=代理端地址，不填默认使用作者地址
    volumes:
      - ./config.yaml:/wx-chatbot/config.yaml
    ports:
      - "8868:8868"
    restart: always
